pkgs: {
  autogenerated-configs = pkgs.callPackage ({stdenv}:
    stdenv.mkDerivation {
      pname = "autogenerated-configs";
      version = "master";

      dontUnpack = true;
      dontBuild = true;

      installPhase = ''
        mkdir -p $out
      '';
    }) {};
}
