{
  imports = [
    ./misc
    ./autocmd.nix
    ./clipboard.nix
    ./colorscheme.nix
    ./commands.nix
    ./diagnostics.nix
    ./doc.nix
    ./editorconfig.nix
    ./filetype.nix
    ./highlights.nix
    ./keymaps.nix
    ./lua-loader.nix
    ./opts.nix
    ./output.nix
    ./plugins.nix
  ];
}
