# Nixvim all maintainers list.
#
# This file combines maintainers from:
# - Nixvim specific maintainers (lib/maintainers.nix)
# - Nixpkgs maintainers referenced in Nixvim modules
#
# This file is automatically generated using meta.maintainers from nixvim evaluation
# DO NOT EDIT MANUALLY
#
# To regenerate: nix run .#generate-all-maintainers
#
{
  # nixvim
  AidanWelch = {
    name = "Aidan Welch";
    email = "aidan@freedwave.com";
    github = "AidanWelch";
    githubId = 35280359;
  };
  # nixvim
  Kareem-Medhat = {
    name = "Kareem Medhat";
    email = "kareemmedhatnabil@gmail.com";
    github = "Kareem-Medhat";
    githubId = 39652808;
  };
  # nixvim
  alisonjenkins = {
    name = "Alison Jenkins";
    email = "alison.juliet.jenkins@gmail.com";
    github = "alisonjenkins";
    githubId = 1176328;
  };
  # nixvim
  b3nb5n = {
    name = "Ben";
    email = "benbaldwin000@gmail.com";
    github = "b3nb5n";
    githubId = 67534814;
  };
  # nixvim
  braindefender = {
    name = "Nikita Shirokov";
    email = "braindefender@gmail.com";
    github = "braindefender";
    githubId = 4646110;
  };
  # nixvim
  elythh = {
    name = "gwen";
    email = "gwen@omg.lol";
    github = "elythh";
    githubId = 50964650;
  };
  # nixvim
  insipx = {
    name = "Andrew Plaza";
    email = "github.tech@liquidthink.net";
    github = "insipx";
    githubId = 6452260;
  };
  # nixvim
  jalil-salame = {
    name = "Jalil David Salamé Messina";
    email = "jalil.salame@gmail.com";
    github = "jalil-salame";
    githubId = 60845989;
    keys = [ { fingerprint = "7D6B 4D8F EBC5 7CBC 09AC  331F DA33 17E7 5BE9 485C"; } ];
  };
  # nixvim
  psfloyd = {
    name = "Pedro Sánchez";
    email = "peter.racoon@gmail.com";
    github = "psfloyd";
    githubId = 30784060;
  };
  # nixvim
  refaelsh = {
    name = "Refael Sheinker";
    email = "refaelsh@pm.me";
    github = "refaelsh";
    githubId = 2750775;
  };
  # nixvim
  sheemap = {
    name = "sheemap";
    github = "sheemap";
    githubId = 1442292;
  };
  # nixvim
  wadsaek = {
    name = "Esther";
    email = "wadsaek@gmail.com";
    github = "wadsaek";
    githubId = 141351086;
  };
  # nixvim
  wvffle = {
    name = "Kasper Seweryn";
    email = "nixvim@wvffle.net";
    github = "wvffle";
    githubId = 13330620;
  };
  # nixpkgs
  "347Online" = {
    name = "Katie Janzen";
    email = "katiejanzen@347online.me";
    github = "347Online";
    githubId = 38228372;
  };
  # nixpkgs
  "4lxs" = {
    name = "svl";
    github = "4lxs";
    githubId = 66408983;
    matrix = "@gyn:matrix.org";
  };
  # nixpkgs
  Balssh = {
    name = "George Bals";
    email = "george.bals25@gmail.com";
    github = "Balssh";
    githubId = 82440615;
  };
  # nixpkgs
  Bodleum = {
    name = "Daniel Laing";
    email = "daniel@daniellaing.com";
    github = "Bodleum";
    githubId = 60107449;
    matrix = "@bodleum:matrix.org";
    keys = [ { fingerprint = "0821 8B96 DC73 85E5 BB7C  A535 D264 3BD2 13BC 0FA8"; } ];
  };
  # nixpkgs
  DataHearth = {
    name = "DataHearth";
    email = "dev@antoine-langlois.net";
    github = "DataHearth";
    githubId = 28595242;
    keys = [ { fingerprint = "E8F9 0B80 908E 723D 0EDF  0916 5803 CDA5 9C26 A96A"; } ];
  };
  # nixpkgs
  Eveeifyeve = {
    name = "Eveeifyeve";
    email = "eveeg1971@gmail.com";
    github = "Eveeifyeve";
    githubId = 88671402;
    matrix = "@eveeifyeve:matrix.org";
  };
  # nixpkgs
  FKouhai = {
    name = "Fran Cirka";
    email = "frandres00@gmail.com";
    github = "FKouhai";
    githubId = 24593008;
  };
  # nixpkgs
  GGORG0 = {
    name = "GGORG";
    email = "GGORG0@protonmail.com";
    github = "GGORG0";
    githubId = 51029895;
    matrix = "@ggorg:matrix.org";
  };
  # nixpkgs
  GaetanLepage = {
    name = "Gaetan Lepage";
    email = "gaetan@glepage.com";
    github = "GaetanLepage";
    githubId = 33058747;
  };
  # nixpkgs
  HeitorAugustoLN = {
    name = "Heitor Augusto";
    email = "IAm.HeitorALN@proton.me";
    github = "HeitorAugustoLN";
    githubId = 44377258;
  };
  # nixpkgs
  MarcelCoding = {
    name = "Marcel";
    email = "me@m4rc3l.de";
    github = "MarcelCoding";
    githubId = 34819524;
  };
  # nixpkgs
  MattSturgeon = {
    name = "Matt Sturgeon";
    email = "matt@sturgeon.me.uk";
    github = "MattSturgeon";
    githubId = 5046562;
    matrix = "@mattsturg:matrix.org";
    keys = [ { fingerprint = "7082 22EA 1808 E39A 83AC  8B18 4F91 844C ED1A 8299"; } ];
  };
  # nixpkgs
  NickHu = {
    name = "Nick Hu";
    email = "me@nickhu.co.uk";
    github = "NickHu";
    githubId = 450276;
  };
  # nixpkgs
  axelkar = {
    name = "Axel Karjalainen";
    email = "axel@axka.fi";
    github = "axelkar";
    githubId = 120189068;
  };
  # nixpkgs
  bkp5190 = {
    name = "Boney Patel";
    email = "boneypatel37@yahoo.com";
    github = "bkp5190";
    githubId = 60232782;
  };
  # nixpkgs
  bpeetz = {
    name = "Benedikt Peetz";
    email = "benedikt.peetz@b-peetz.de";
    github = "bpeetz";
    githubId = 140968250;
    matrix = "@soispha:vhack.eu";
    keys = [ { fingerprint = "8321 ED3A 8DB9 99A5 1F3B  F80F F268 2914 EA42 DE26"; } ];
  };
  # nixpkgs
  f4z3r = {
    name = "Jakob Beckmann";
    email = "f4z3r-github@pm.me";
    github = "f4z3r";
    githubId = 32326425;
    keys = [ { fingerprint = "358A 6251 E2ED EDC1 9717  14A7 96A8 BA6E C871 2183"; } ];
  };
  # nixpkgs
  foo-dogsquared = {
    name = "Gabriel Arazas";
    email = "foodogsquared@foodogsquared.one";
    github = "foo-dogsquared";
    githubId = 34962634;
    matrix = "@foodogsquared:matrix.org";
    keys = [ { fingerprint = "DDD7 D0BD 602E 564B AA04  FC35 1431 0D91 4115 2B92"; } ];
  };
  # nixpkgs
  getchoo = {
    name = "Seth Flynn";
    email = "getchoo@tuta.io";
    github = "getchoo";
    githubId = 48872998;
    matrix = "@getchoo:matrix.org";
  };
  # nixpkgs
  hmajid2301 = {
    name = "Haseeb Majid";
    email = "hello@haseebmajid.dev";
    github = "hmajid2301";
    githubId = 998807;
    keys = [ { fingerprint = "A236 785D 59F1 9076 1E9C E8EC 7828 3DB3 D233 E1F9"; } ];
  };
  # nixpkgs
  janurskremer = {
    name = "Jan Kremer";
    email = "mail@jankremer.eu";
    github = "janurskremer";
    githubId = 79042825;
    matrix = "@jankremer:matrix.org";
    keys = [ { fingerprint = "20AF 0A65 9F2B 93AD 9184  15D1 A7DA 689C B3B0 78EC"; } ];
  };
  # nixpkgs
  jolars = {
    name = "Johan Larsson";
    email = "jolars@posteo.com";
    github = "jolars";
    githubId = 13087841;
    matrix = "@jola:mozilla.org";
    keys = [ { fingerprint = "F0D6 BDE7 C7D1 6B3F 7883  73E7 2A41 C0FE DD6F F540"; } ];
  };
  # nixpkgs
  kalbasit = {
    name = "Wael Nasreddine";
    email = "wael.nasreddine@gmail.com";
    github = "kalbasit";
    githubId = 87115;
    matrix = "@kalbasit:matrix.org";
  };
  # nixpkgs
  khaneliman = {
    name = "Austin Horstman";
    email = "khaneliman12@gmail.com";
    github = "khaneliman";
    githubId = 1778670;
  };
  # nixpkgs
  loicreynier = {
    name = "Loïc Reynier";
    email = "loic@loicreynier.fr";
    github = "loicreynier";
    githubId = 88983487;
  };
  # nixpkgs
  mitchmindtree = {
    name = "Mitchell Nordine";
    email = "mail@mitchellnordine.com";
    github = "mitchmindtree";
    githubId = 4587373;
  };
  # nixpkgs
  nfelber = {
    name = "Nathan Felber";
    email = "nathan@pascaline.org";
    github = "nfelber";
    githubId = 46248772;
  };
  # nixpkgs
  nwjsmith = {
    name = "Nate Smith";
    email = "nate@theinternate.com";
    github = "nwjsmith";
    githubId = 1348;
  };
  # nixpkgs
  onemoresuza = {
    name = "Coutinho de Souza";
    email = "dev@onemoresuza.com";
    github = "onemoresuza";
    githubId = 106456302;
    keys = [ { fingerprint = "6FD3 7E64 11C5 C659 2F34  EDBC 4352 D15F B177 F2A8"; } ];
  };
  # nixpkgs
  polnio = {
    name = "Po Co";
    email = "polniolino@gmail.com";
    github = "polnio";
    githubId = 85367527;
  };
  # nixpkgs
  theabm = {
    name = "Andres Bermeo Marinelli";
    email = "andres_bermeo@outlook.com";
    github = "theabm";
    githubId = 72303015;
  };
  # nixpkgs
  traxys = {
    name = "Quentin Boyer";
    email = "quentin+dev@familleboyer.net";
    github = "traxys";
    githubId = 5623227;
  };
  # nixpkgs
  zainkergaye = {
    name = "Zain Kergaye";
    email = "zain@zkergaye.me";
    github = "zainkergaye";
    githubId = 62440012;
  };
}
