# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  coq-artifacts = {
    pname = "coq-artifacts";
    version = "ee1814e2183bd424ca5528f82f3d6ce8f64e6f90";
    src = fetchFromGitHub ({
      owner = "ms-jpq";
      repo = "coq.artifacts";
      rev = "ee1814e2183bd424ca5528f82f3d6ce8f64e6f90";
      fetchSubmodules = false;
      sha256 = "sha256-e+w5tLuer/4f0oImlIgxmI4Ke9h6x0PQ8+nVJDihkGQ=";
    });
    date = "2023-03-12";
  };
  coq-nvim = {
    pname = "coq-nvim";
    version = "4b4b93dbbfc871a3d32a244a4276ee06696c21bb";
    src = fetchFromGitHub ({
      owner = "ms-jpq";
      repo = "coq_nvim";
      rev = "4b4b93dbbfc871a3d32a244a4276ee06696c21bb";
      fetchSubmodules = false;
      sha256 = "sha256-OXhLs7fO+qlOPyDc8AOA+bkbj9OzMZO8CFgfE/Q1cro=";
    });
    date = "2023-03-12";
  };
  inc-rename = {
    pname = "inc-rename";
    version = "21c23c379342a731a0c90f226601ec0434627b26";
    src = fetchFromGitHub ({
      owner = "smjonas";
      repo = "inc-rename.nvim";
      rev = "21c23c379342a731a0c90f226601ec0434627b26";
      fetchSubmodules = false;
      sha256 = "sha256-KxXVe0amA0tyU6J2M+4XERSyERWS4BqGuxmbJ9YUyRs=";
    });
    date = "2023-01-29";
  };
  intellitab-nvim = {
    pname = "intellitab-nvim";
    version = "a6c1a505865f6131866d609c52440306e9914b16";
    src = fetchFromGitHub ({
      owner = "pta2002";
      repo = "intellitab.nvim";
      rev = "a6c1a505865f6131866d609c52440306e9914b16";
      fetchSubmodules = false;
      sha256 = "sha256-z5G7v2OttQs5B/uqWdxYtW6wPnVPARjQYidKLYkhvqY=";
    });
    date = "2021-11-13";
  };
  magma-nvim = {
    pname = "magma-nvim";
    version = "5d916c39c1852e09fcd39eab174b8e5bbdb25f8f";
    src = fetchFromGitHub ({
      owner = "WhiteBlackGoose";
      repo = "magma-nvim-goose";
      rev = "5d916c39c1852e09fcd39eab174b8e5bbdb25f8f";
      fetchSubmodules = false;
      sha256 = "sha256-Sq7J43AYvsfUdFXELzEwBNTpnOt/F43/de+2zwBspoE=";
    });
    date = "2023-03-13";
  };
  mark-radar = {
    pname = "mark-radar";
    version = "d7fb84a670795a5b36b18a5b59afd1d3865cbec7";
    src = fetchFromGitHub ({
      owner = "winston0410";
      repo = "mark-radar.nvim";
      rev = "d7fb84a670795a5b36b18a5b59afd1d3865cbec7";
      fetchSubmodules = false;
      sha256 = "sha256-6WfEFLFQnDpQ2X0NRSa25ALvm/SxiFoW4PAzBA8TdPg=";
    });
    date = "2021-06-22";
  };
  netman-nvim = {
    pname = "netman-nvim";
    version = "1ef50efcbe88f8293e97946af37243a20873bb1c";
    src = fetchFromGitHub ({
      owner = "miversen33";
      repo = "netman.nvim";
      rev = "1ef50efcbe88f8293e97946af37243a20873bb1c";
      fetchSubmodules = false;
      sha256 = "sha256-oRjBjVmO/7bmgyf9ltthRrwZBD5SLD757GklSjw1bJs=";
    });
    date = "2023-03-02";
  };
  nvim-osc52 = {
    pname = "nvim-osc52";
    version = "47ce7ee2396fa3ee4fb6b0e0ef14ba06f9c9bd31";
    src = fetchFromGitHub ({
      owner = "ojroques";
      repo = "nvim-osc52";
      rev = "47ce7ee2396fa3ee4fb6b0e0ef14ba06f9c9bd31";
      fetchSubmodules = false;
      sha256 = "sha256-SQpwiA+dyTRXBq0YtUZ4nkYKglyChIyQeWopD73qznQ=";
    });
    date = "2023-03-03";
  };
  pynvim_pp = {
    pname = "pynvim_pp";
    version = "40db0426f171d413dcc976b17c8eff0127664f23";
    src = fetchFromGitHub ({
      owner = "ms-jpq";
      repo = "pynvim_pp";
      rev = "40db0426f171d413dcc976b17c8eff0127664f23";
      fetchSubmodules = false;
      sha256 = "sha256-AtsoRJQcO5jDNlSydVnqcN7f4xURmH6bGFPpjsZ9Yrg=";
    });
    date = "2023-03-12";
  };
  std2 = {
    pname = "std2";
    version = "43635e036486296776b4ef5ac498f742ad25a691";
    src = fetchFromGitHub ({
      owner = "ms-jpq";
      repo = "std2";
      rev = "43635e036486296776b4ef5ac498f742ad25a691";
      fetchSubmodules = false;
      sha256 = "sha256-oWVaw7v1Sl7DkqIJOm8wEReID9MTD3XFOdpyQDXRa04=";
    });
    date = "2023-03-12";
  };
}
