# This file contains a list of function reference docs pages that should be generated by `nixdoc`
#
# Note: `nixdoc` uses `rnix` to parse the input file, so the file must return a fairly simple attrset.
# If there is an issue parsing the file, the resulting markdown will not contain any function docs.

{
  lib.nixvim = {
    _page = {
      title = "Nixvim's functions";
      source = ./index.md;
    };

    utils._page = {
      title = "utility functions";
      functions.file = ../../lib/utils.nix;
    };
    lua._page = {
      title = "lua functions";
      functions.file = ../../lib/to-lua.nix;
    };
  };
}
