{
  lib,
  callPackage,
  writeShellApplication,
}:
let
  mainInfo = callPackage ./main.nix { };
in
writeShellApplication {
  name = "version-info";
  text = ''
    (
      echo "# DO NOT MODIFY!"
      echo "# This file was generated by ${
        lib.strings.removePrefix (toString ../.. + "/") (toString ./default.nix)
      }"
      cat ${mainInfo}
    ) > version-info.toml
  '';
}
