.TH "NIXVIM" "5" "01/01/1980" "Nixvim" "Nixvim Reference Pages"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" enable line breaks after slashes
.cflags 4 /
.SH "NAME"
Nixvim options specification
.SH "DESCRIPTION"
.PP
This page lists all the options that can be used in Nixvim. It can either be used as a Home Manager module, an NixOS module or a standalone package. Please refer to the installation instructions for more details.
