name: PR

on:
  pull_request_target:

concurrency:
  group: pr-${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}

  # This job posts the "Required Status Checks" to satisfy our ruleset.
  required-checks:
    # It "needs" all the jobs that should block merging a PR.
    # Modify this list to add or remove jobs from required status checks.
    needs:
      - lint

    name: Required checks
    runs-on: ubuntu-24.04-arm
    permissions:
      statuses: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const { serverUrl, repo, runId, payload } = context
            await github.rest.repos.createCommitStatus({
              ...repo,
              sha: payload.pull_request.head.sha,
              target_url: `${serverUrl}/${repo.owner}/${repo.repo}/actions/runs/${runId}`,
              // WARNING:
              // Do NOT change the context name or it will not match the ruleset.
              // This would prevent all PRs from merging.
              context: 'PR checks successful',
              state: 'success',
            })
