import json
import os
import sys
from collections import defaultdict

from nixos_render_docs.options import CommonMarkConverter
from nixos_render_docs.types import AnchorStyle


def render_option_markdown(converter, name, rendered):
    """
    Reproduce the output generated by CommonMarkConverter.finalize() for a single option.
    """

    # NOTE: internal nixos-option-docs API
    anchor_suffix = converter._make_anchor_suffix(rendered.loc)

    result = [
        f"## {name}{anchor_suffix}\n",
        *rendered.lines,
        "\n\n",
    ]

    return "\n".join(result)


def render_sections(attrs, converter):
    # Input shape:
    #
    # {
    #   "options": {
    #     "section-id": {
    #       "plugins.zk.enable": { ... },
    #       ...
    #     },
    #     "another-section-id": {
    #       ...
    #     }
    #   }
    # }
    section_membership = defaultdict(list)
    all_options = {}

    for section_id, section_options in attrs["options"].items():
        for option_name, option in section_options.items():
            all_options[option_name] = option
            section_membership[section_id].append(option_name)

    # Expensive phase.
    #
    # This is where upstream performs:
    #
    #   parallel.map(...)
    #
    # and populates:
    #
    #   converter._options
    converter.add_options(all_options)

    # Build section markdown from RenderedOption objects.
    result = {}

    for section_id, option_names in section_membership.items():
        parts = []

        for option_name in option_names:
            # NOTE: internal nixos-option-docs API
            rendered = converter._options[option_name]

            parts.append(
                render_option_markdown(
                    converter,
                    option_name,
                    rendered,
                )
            )

        result[section_id] = "".join(parts)

    return result


def main():
    nixpkgs_revision = os.environ["NIXPKGS_REVISION"]

    with open(os.environ["NIX_ATTRS_JSON_FILE"]) as f:
        attrs = json.load(f)

    with open(os.environ["MANPAGE_URLS"]) as f:
        manpage_urls = json.load(f)

    converter = CommonMarkConverter(
        manpage_urls,
        revision=nixpkgs_revision,
        anchor_style=AnchorStyle.LEGACY,
        anchor_prefix="opt-",
    )

    result = render_sections(attrs, converter)
    json.dump(result, sys.stdout, sort_keys=True, indent=2)


if __name__ == "__main__":
    main()
